name: flutter_bloc_app_template
description: The project of the empty template with Flutter has built the basic framework to realize the functions of internationalization, theme peeling etc.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  logger: ^1.1.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  dio: ^4.0.4
  intl: ^0.17.0
  google_fonts: ^2.3.1
  #analyzer: ^2.7.0
  intl_utils: ^2.6.1
  effective_dart: ^1.3.2
  flutter_svg: ^1.0.3
  gap: ^2.0.0
  go_router: ^3.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.5
  freezed: ">=1.0.0 <1.1.1"
  #coverage: ^1.1.0
  lint: ^1.8.2
  mockito: ^5.1.0
  #test: ^1.17.9
  bloc_test: ^9.0.3
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0
  dart_code_metrics: ^4.14.0
  network_image_mock: ^2.1.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - google_fonts/
  fonts:
    - family: Roboto
      fonts:
        - asset: google_fonts/Roboto-Medium.ttf
          weight: 500

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true