name: core
description: The core module
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.1"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.14.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: dev.shtanko.core
    iosBundleIdentifier: dev.shtanko.core

flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true

  colors:
    inputs:
      - assets/color/colors.xml